document:
  name: Specifiche Attuative Nodo (SANP)
  description: |
    Il presente documento denominato “Specifiche Attuative 
    del Nodo dei Pagamenti-SPC” rappresenta l’Allegato B alle 
    “Linee guida per l'effettuazione dei pagamenti a favore  	
    delle pubbliche amministrazioni e dei gestori di pubblici servizi” 
    e deve essere utilizzato in combinazione con il documento 
    "Specifiche attuative dei codici identificativi di versamento,
    riversamento e rendicontazione" 
    (Allegato A), nonché con le stesse Linee guida; 
    documenti ai quali si rimanda per tutte le voci e gli 
    argomenti non specificatamente qui indicati.    
  tags:
    - Guida per gli esercenti
    - esercenti
    - Piano di sviluppo
    - DAF Dataportal
    - DAF
    - Linee guida Pubblica Amministrazione
    - Pubblica Amministrazione
    - pagoPA
    - PA
    - Pagamenti-SPC
    - Docs Italia
    - Nodo dei Pagamenti-SPC
    - SPC
    - PSP
    - AgID 
    - SEPA
    - SIPA
    - SPCoop
    - Web-FESP
    - WISP
    - FESP
    - IUV
    - SACI
    - SANP
    - Nodo
    - CAD
    - CCP
    - Certificato digitale
    - Ente Aggregatore
    - ER
    - Initiating Party
    - PdD
    - PdDE
    - Bollo Digitale
    - RT
    - RPT
    - Seller Bank
    - Linee guida